(ns mealy.ooda.prompt
  "Pure functions to compile Cell state into LLM prompts.
   Implements the 'Source Code as Prompt' strategy by inlining the frozen
   kernel and bootstrap source into the LLM's context window."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [mealy.action.core :as action]
            [mealy.subscription.core :as sub]))

;; ---------------------------------------------------------------------------
;; System Prompts (role-specific personas)
;; ---------------------------------------------------------------------------

(def sociocratic-system-prompt
  "The hardcoded deterministic cognitive routing engine persona."
  "You are the deterministic cognitive routing engine for an autonomous agent. Your ONLY purpose is to evaluate the user's provided State and Proposed Action against the Aim, Memory, and Policies. You do not converse. You do not offer help. If the Proposed Action does not critically harm the Aim, violate Memory constraints, or contravene any Policy, you MUST output exactly: 'CONSENT: [brief reason]'. If it violates a critical constraint or Policy, output exactly: 'OBJECTION: [reason]'.")

(def agentic-system-prompt
  "The generative cognitive engine persona."
  (str "You are an autonomous Mealy Cell — a pure state machine with Sans-IO boundaries.\n"
       "You are autonomous. The Anchor (human) defines only your Aim and consents to Policies.\n"
       "You manage everything else: event handling, skill acquisition, resource management,\n"
       "and specialization through mitosis.\n\n"
       "You must evaluate your State, Aim, and Options and propose zero or more precise Actions.\n"
       "You must reply strictly with a Clojure EDN array of action maps.\n"
       "Each action is a map with a :type key. Example: [{:type :propose :prompt \"write a handler for :rss-check\"}].\n"
       "Do not include any other text, markdown, or native tool calls."))

(def code-gen-system-prompt
  "The pure code generation persona."
  (str "You are an expert Clojure software engineer. Your task is to write Clojure code based on the provided prompt and state.\n"
       "Only output valid, pure Clojure code strings. Do not include markdown blocks, explanations, or backticks.\n"
       "IMPORTANT: Since your code is evaluated in a strict SCI sandbox, you must ONLY extend the system by:\n"
       "- Defining methods: (defmethod mealy.cell.reducer/handle-event :my-event [state [_ data]] ...)\n"
       "- Defining action executors: (defmethod mealy.action.core/execute :my-action [action env] ...)\n"
       "CRITICAL: handle-event methods MUST return a MAP {:state <new-state> :actions [<action-maps>]}.\n"
       "Do NOT return a vector [state actions]. This will break the system.\n"
       "Example: {:state (assoc state :foo 1) :actions [{:type :think :prompt \"reflect\"}]}\n"
       "Available namespaces: mealy.cell.reducer, mealy.action.core, mealy.intelligence.llm, mealy.ooda.prompt, mealy.cell.mitosis, clojure.string, clojure.core.async"))

(def code-review-system-prompt
  "Persona for reviewing candidate code before live execution."
  (str "You are a senior Clojure software engineer reviewing code generated by an autonomous agent.\n"
       "Your task is to analyze the proposed Clojure code and decide whether to approve it.\n"
       "Ensure it strictly extends either `mealy.action.core/execute` or `mealy.cell.reducer/handle-event`.\n"
       "CRITICAL CHECK: handle-event methods MUST return a MAP {:state <new-state> :actions [...]}.\n"
       "If the code returns a vector like [state actions] instead of a map, that is WRONG — OBJECTION.\n"
       "Provide your critique. If the code looks syntactically correct and logical, YOU MUST CONCLUDE WITH THE EXACT WORD 'CONSENT'.\n"
       "If it has logic errors, returns wrong types, hallucinates unavailable functions, or violates boundaries, YOU MUST CONCLUDE WITH THE EXACT WORD 'OBJECTION' along with your reasoning."))

;; ---------------------------------------------------------------------------
;; Dynamic introspection helpers
;; ---------------------------------------------------------------------------

(defn get-available-actions
  "Dynamically inspects the mealy.action.core/execute multimethod to extract
  the currently registered actions and their docstrings."
  []
  (let [methods-map (methods action/execute)
        action-descriptions (for [[dispatch-val method-fn] methods-map
                                  :let [docstring (:doc (meta method-fn))
                                        desc (or docstring "No description available.")]]
                              (str "- " dispatch-val ": " desc))]
    (str/join "\n" (sort action-descriptions))))

(defn get-available-reducer-events
  "Dynamically inspects the mealy.cell.reducer/handle-event multimethod to extract
  the currently registered events."
  []
  (if-let [mf (resolve 'mealy.cell.reducer/handle-event)]
    (let [methods-map (methods @mf)
          events (for [[dispatch-val _] methods-map
                       :when (keyword? dispatch-val)]
                   (str "- " dispatch-val))]
      (str/join "\n" (sort events)))
    "- Unknown (Multimethod not loaded)"))

(defn get-available-bus-topics
  "Dynamically inspects the start-subscription multimethod to extract
  the currently registered source types and their docstrings."
  []
  (let [methods-map (dissoc (methods sub/start-subscription) :default)
        descriptions (for [[dispatch-val method-fn] methods-map
                           :let [docstring (:doc (meta method-fn))
                                 desc (or docstring "No description available.")]]
                       (str "- " dispatch-val ": " desc))]
    (str/join "\n" descriptions)))

;; ---------------------------------------------------------------------------
;; Unified state serialization
;; ---------------------------------------------------------------------------

(defn- format-policies
  "Formats a vector of policies into a numbered list string."
  [policies]
  (if (seq policies)
    (str/join "\n" (map-indexed (fn [i p] (str (inc i) ". " p)) policies))
    "(none)"))

(defn compile-bootstrap-context
  "Compiles the Cell's bootstrap source code into a context string.
   This gives the LLM visibility into its own cognitive architecture."
  []
  (if-let [res (io/resource "bootstrap.clj")]
    (let [source (slurp res)]
      (str "\nYour OODA Cognitive Pipeline (modifiable via :propose):\n"
           "```clojure\n" source "\n```"))
    ""))

(defn compile-state-context
  "Compiles the Cell's state into a context string for LLM consumption.
   This is the unified state serializer — all prompt functions use this.
   Options:
     :max-observations    — limit recent observations (default: all)
     :include-memory      — include memory section (default: true)
     :exclude-memory-keys — set of keys to omit from memory (default: nil)
     :include-actions     — include action/event/topic introspection (default: true)
     :include-bootstrap   — include bootstrap source code (default: true)"
  [state & {:keys [max-observations include-memory exclude-memory-keys
                   include-actions include-bootstrap]
            :or {include-memory true include-actions true include-bootstrap true}}]
  (let [{:keys [aim memory observations policies phase bus-topics]} state
        filtered-memory (if exclude-memory-keys
                          (apply dissoc memory exclude-memory-keys)
                          memory)
        obs (if max-observations
              (take-last max-observations observations)
              observations)]
    (str "Aim: " aim "\n"
         "Phase: " (name (or phase :idle)) "\n"
         "Policies:\n" (format-policies policies) "\n\n"
         (when include-memory
           (str "Memory:\n" (pr-str filtered-memory) "\n\n"))
         "Observations:\n" (pr-str obs) "\n"
         (when (seq bus-topics)
           (str "\nEventBus topics: "
                (str/join ", " (map name bus-topics)) "\n"))
         (when include-actions
           (str "\nAvailable Actions:\n" (get-available-actions) "\n"
                "\nAvailable Reducer Events:\n" (get-available-reducer-events) "\n"
                "\nAvailable Sources (Bus Topics):\n" (get-available-bus-topics)))
         (when include-bootstrap
           (compile-bootstrap-context)))))

(defn compile-think-system-prompt
  "Compiles a system prompt for the :think action, giving the LLM
   context about the Cell's aim, state, and Clojure environment."
  [state]
  (str "You are an autonomous Mealy Cell — a Clojure-based agentic state machine.\n"
       "Use Clojure idioms and data structures in any code examples.\n"
       "Think step-by-step and be concise.\n\n"
       (compile-state-context state
                              :max-observations 5
                              :include-actions true
                              :include-bootstrap false)))

;; ---------------------------------------------------------------------------
;; Prompt compilation functions (used by bootstrap.clj handlers)
;; ---------------------------------------------------------------------------

(defn compile-prompt
  "Compiles the Cell's state into a Consent-based LLM evaluation prompt string.
   Used by the sociocratic consent handler."
  [state]
  (str "Consent-based LLM evaluation\n\n"
       (compile-state-context state)))

(defn compile-agentic-prompt
  "Compiles the Cell's state into an Agentic Generative LLM evaluation prompt string.
   Used by the :orient handler to generate actions."
  [state]
  (str "Agentic Action Generation\n\n"
       (compile-state-context state :max-observations 10) "\n\n"
       "Provide actions to progress the Aim. If none apply, return []."))

(defn compile-policy-evaluation-prompt
  "Compiles an LLM prompt for the cell to evaluate a proposed policy change
  against its current Aim, Memory, and existing Policies."
  [state proposed-policy]
  (str "A policy change has been proposed for your consent.\n\n"
       "Current Aim: " (:aim state) "\n"
       "Current Policies:\n" (format-policies (:policies state)) "\n\n"
       "Proposed New Policy: " proposed-policy "\n\n"
       "Evaluate whether this proposed policy is consistent with the Aim and "
       "does not contradict existing Policies.\n"
       "If acceptable, respond with: CONSENT: [brief reason]\n"
       "If problematic, respond with: OBJECTION: [reason]"))

(defn compile-tap-system-prompt
  "Compiles a system prompt for a tap interaction, giving the LLM context
   about the cell's full state using compile-state-context for consistency.
   Adds a conversational persona and the current time."
  [state]
  (let [current-time (get-in state [:memory :current-time] "unknown")]
    (str "You are an autonomous Mealy cell. A human colleague is checking in with you.\n"
         "Current time: " current-time "\n\n"
         (compile-state-context state :max-observations 5 :exclude-memory-keys #{:chat} :include-bootstrap false) "\n\n"
         "Respond concisely and helpfully. Be conversational. "
         "If the user asks you to perform an action or if you think an action is appropriate, "
         "you may append a Clojure EDN array of action maps to your response "
         "(e.g. `[{:type :propose :prompt \"...\"}]`).")))
